name: LightningRunner Parallel-Check

on:
  workflow_dispatch:        # run it manually or change to `push:` etc.

jobs:
  # ─────────── Matrix fan-out ───────────
  parallel-test:
    runs-on: ["self-hosted", "lightning-fast"]
    strategy:
      fail-fast: false
      max-parallel: 9          # GitHub will schedule up to 9 at once
      matrix:
        job_id: [1,2,3,4,5,6,7,8,9]
    outputs:
      host-${{ matrix.job_id }}: ${{ steps.capture.outputs.host }}
      start-${{ matrix.job_id }}: ${{ steps.capture.outputs.start }}
    steps:
      - name: Capture host & timestamp
        id: capture
        run: |
          HOST=$(hostname)
          START=$(date '+%H:%M:%S')
          echo "Running job ${{ matrix.job_id }} on $HOST at $START"
          echo "::set-output name=host::$HOST"
          echo "::set-output name=start::$START"

      - name: Simulate 30-second workload
        run: sleep 30

  # ─────────── Collect & print results ───────────
  summarise:
    needs: parallel-test
    runs-on: ubuntu-latest
    steps:
      - name: Show which host ran which job
        run: |
          echo "Job  Host        StartTime"
          echo "---- ----------- ----------"
          for i in {1..9}; do
            HOST=$(echo "${{ needs.parallel-test.outputs['host-'$i] }}")
            START=$(echo "${{ needs.parallel-test.outputs['start-'$i] }}")
            printf "%-4s %-11s %s\n" "$i" "$HOST" "$START"
          done
