name: LightningRunner Parallel-Check

on:
  workflow_dispatch:       # run manually; change to "push:" if desired

jobs:
  # ───────── 1. Fan-out matrix ─────────
  parallel-test:
    runs-on: ["self-hosted", "lightning-fast"]
    strategy:
      fail-fast: false
      max-parallel: 9
      matrix:
        job_id: [1,2,3,4,5,6,7,8,9]

    steps:
      - name: Capture host & timestamp
        run: |
          HOST=$(hostname)
          START=$(date '+%H:%M:%S')
          echo "job=${{ matrix.job_id }}"   >  result.txt
          echo "host=${HOST}"              >> result.txt
          echo "start=${START}"            >> result.txt
          cat  result.txt                  # show in logs

      - name: Simulate 30-second workload
        run: sleep 30

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.job_id }}
          path: result.txt

  # ───────── 2. Fan-in summary ─────────
  summarise:
    needs: parallel-test
    runs-on: ubuntu-latest
    steps:
      - name: Download all result artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: result-*                # grab all nine

      - name: Print table
        run: |
          printf "%-4s %-15s %s\n" "Job" "Host" "StartTime"
          printf "%-4s %-15s %s\n" "----" "---------------" "---------"
          for f in result-*/result.txt; do
            source "$f"   # sets $job, $host, $start
            printf "%-4s %-15s %s\n" "$job" "$host" "$start"
          done
